In [2]:
import numpy as np

Filtrando arrays

Quando queremos filtrar os dados com base em condições que eles apresentam.

Indexação sofisticada (fancy indexing) ou usando máscara (mask) em array 2d

Exemplo: Queremos descobrir quais valores são divisíveis por 2.

Recebemos uma resposta em booleanos

In [3]:
pessoas_id_idade = np.array([[1, 22], [2, 21], [3, 27], [4, 26]])
pessoas_id_idade[:, 1] % 2 == 0

array([ True, False, False,  True])

Retornar pessoas com idade maior que 21

In [12]:
mask_maior21 = pessoas_id_idade[:, 1] > 21
pessoas_id_idade[mask_maior21]


array([[ 1, 22],
       [ 3, 27],
       [ 4, 26]])

Exemplo com mask - retorna booleano de true ou false.

In [4]:
arr1 = np.array([1, 2, 3, 4, 5])
mask = arr1 % 2 == 0
mask

array([False,  True, False,  True, False])

Exemplo com fancy indexing - Retorna valores do array quando passado a máscara

In [5]:
arr1[mask]

array([2, 4])

np.where() - retorna um array de indices e cria uma matriz com base nas condições dadas e os elementos que correspondem a estas condições.

No exemplo a baixo, ele retornou [0, 3] que correspondem ao 22 e ao 26.



In [6]:
pessoas_id_idade = np.array([[1, 22], [2, 21], [3, 27], [4, 26]])
np.where(pessoas_id_idade[:, 1] % 2 == 0)

(array([0, 3]),)

np.where com fancy indexing - irá retornar a localização do elemento na matriz.

Pelo exemplo abaixo, ele retornou linhas [0, 0, 1, 2, 2, 3] e depois colunas [2, 3, 3, 0, 2, 2], que na ordem simultaneamente, indicam um elemento.

[0, 2] = linha 0 e coluna 2 = 3

[0, 3] = linha 0 e coluna 3 = 15

[1, 3] = linha 1 e coluna 3 = 27

etc

In [8]:
cartela_bingo = np.array([[16, 10, 3, 15],
                       [14, 23, 17, 27],
                       [6, 19, 3 , 1],
                       [10, 4, 18, 19]])
cartela_bingo


array([[16, 10,  3, 15],
       [14, 23, 17, 27],
       [ 6, 19,  3,  1],
       [10,  4, 18, 19]])

In [9]:
np.where(cartela_bingo % 3 == 0)

(array([0, 0, 1, 2, 2, 3]), array([2, 3, 3, 0, 2, 2]))

Buscar e Substituir

No exemplo abaixo ele retornou o dtype'<U21' revelando que o array foi transformado em string. Onde se encontravam números divisíveis por 3 no array, será substituído por xxx.

In [13]:
np.where(cartela_bingo % 3 == 0, "xxx", cartela_bingo)

array([['16', '10', 'xxx', 'xxx'],
       ['14', '23', '17', 'xxx'],
       ['xxx', '19', 'xxx', '1'],
       ['10', '4', 'xxx', '19']], dtype='<U21')

Atividade - Ainda usando o array de espécies marítimas.

Usando um index booleano, crie um array que contém os dados da maior espécie encontrada (considerando seu tamanho), esse valor corresponde ao valor 22.

Usando fancy index faça um array que contém apenas dados da espécie com ID 297.

Usando np.where() fala um array com a linha com dados correspondentes a espécie com 105 representandtes encontrados.

Considere a profundeza em que a espécie foi encontttrada e substitua valores maiores que 60 por "Profundo"

In [14]:
especies = np.array([[747, 89, 33, 5],
                    [623, 123, 32, 13],
                    [501, 22, 49, 2],
                    [116, 101, 42, 10],
                    [297, 56, 69, 22],
                    [613, 64, 27, 7],
                    [295, 84, 29, 14],
                    [692, 105, 72, 16],
                    [229, 103, 35, 5],
                    [374, 124, 70, 1]])
especies

array([[747,  89,  33,   5],
       [623, 123,  32,  13],
       [501,  22,  49,   2],
       [116, 101,  42,  10],
       [297,  56,  69,  22],
       [613,  64,  27,   7],
       [295,  84,  29,  14],
       [692, 105,  72,  16],
       [229, 103,  35,   5],
       [374, 124,  70,   1]])

Usando um index booleano, crie um array que contém os dados da maior espécie encontrada (considerando seu tamanho), esse valor corresponde ao valor 22.

In [15]:
especies[:, 3] == 22

array([False, False, False, False,  True, False, False, False, False,
       False])

In [18]:
maior_especie = especies[especies[:, 3] == 22]
maior_especie

array([[297,  56,  69,  22]])

Usando fancy index faça um array que contém apenas dados da espécie com ID 297.

In [19]:
especies[:, 0] == 297

array([False, False, False, False,  True, False, False, False, False,
       False])

In [20]:
especie297 = especies[especies[:, 0] == 297]
especie297

array([[297,  56,  69,  22]])

Usando np.where() faça um array com a linha com dados correspondentes a espécie com 105 representantes encontrados.

In [21]:
np.where(especies[:, 1] == 105)

(array([7]),)

In [22]:
especies[np.where(especies[:, 1] == 105)]

array([[692, 105,  72,  16]])

Considere a profundeza em que a espécie foi encontttrada e substitua valores maiores que 60 por "Profundo"

Observação - a última sentença com especies[:, 2] precisa ser adicionada, para definir que estamos trabalhando com a mesma quantidade de elementos = 10 linhas e 1 coluna, sem isso daria erro, pois estariamos tentando transformar uma matriz de 40 elementos em uma de 10 elementos, impossibilitando a ação.

In [26]:
especies[:, 2] > 60


array([False, False, False, False,  True, False, False,  True, False,
        True])

In [28]:
especies[:, 2]

array([33, 32, 49, 42, 69, 27, 29, 72, 35, 70])

In [27]:
np.where(especies[:, 2] > 60, "Profundo", especies[:, 2])

array(['33', '32', '49', '42', 'Profundo', '27', '29', 'Profundo', '35',
       'Profundo'], dtype='<U21')