## numpy - biblioteca central para computação científica em python

### Em numpy o array é o objeto principal - estrutura em grades que armazena dados. Pode ter qualquer número de dimensão e cada dimensão pode conter um número muito grande de comprimento, contudo a array só consegue manter um tipo de dado.

### É uma biblioteca que precisa ser importada, conforme código abaixo:

##### shift + enter = rodar o código

In [5]:
import numpy as np

Logo temos um exemplo de array

l = lista

In [ ]:
l = [ 1, 2, 3, 4]
arr1 = np.array(l)

In [ ]:
arr1

array([1, 2, 3, 4])

Criando um numpy array do zero


Nesse primeiro exemplo temos uma array onde você escolhe a dimensão em linhas e colunas, gerando uma array de elementos zeros. Esse np.zeros recebe uma tupla, que são (), a escrita da array já possuí (), recebendo a tupla, ficam duas duplas de (()).

In [ ]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

Aqui temos o exemplo de range, onde você coloca o valor inicial e o valor final e ele dará a ordem em números inteiros. Observe que o 0 está incluído na contagem, mas o 3 não entra. Ou seja, se fosse para o 3 aparecer, teria que ser ((0, 4))

In [ ]:
list(range(0,3))

[0, 1, 2]

Para fazer de 1 até 10, colocamos de 1,11

In [ ]:
arr_range = np.arange(1,11)
arr_range

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Para printar qual o tipo de array que está sendo aplicado, utilizamos o código abaixo:

In [ ]:
type(arr_range)

numpy.ndarray

O último exemplo é para gerar uma array com valores aleatórios, você informa o número de linhas e colunas.

In [ ]:
np.random.random((3,3))

array([[0.56184782, 0.10536512, 0.87581599],
       [0.37376106, 0.48747844, 0.38628155],
       [0.0368891 , 0.41719797, 0.37243085]])

1 - Crie um array com 4 linhas e 3 colunas com valores aleatórios.

In [ ]:
np.random.random((4,3))

array([[0.15718944, 0.4341133 , 0.66417505],
       [0.81331871, 0.86229252, 0.89325172],
       [0.36413998, 0.89839265, 0.66490617],
       [0.49723612, 0.44350471, 0.74634966]])

Crie um array com 5 colunas e 10 linhas iniciazados com zeros.

In [ ]:
np.zeros((10,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

Crie um array com valores inteiros 3 linhas e 5 colunas com valores aleatórios.
Aqui aplicamos um novo método = randint() que nos dará valores inteiros. Nele você deve apontar o intervalo, abaixo colocamos números de 0 a 30, que foi representado somente pelo 30, onde o 30 não irá aparecer e o tamanho do array = 3 linhas e 5 colunas;

Obs: se quisessemos números aleatórios num intervalo de 10 a 30, incluindo o 30, seria escrito np.random.randint(10 ,31, size=(3, 5)), segue logo após.

In [6]:
np.random.randint(30, size=(3, 5))

array([[ 7,  1, 22, 18,  8],
       [19, 22, 10,  9,  6],
       [29, 11,  4, 28,  7]])

In [7]:
np.random.randint(10 ,31, size=(3, 5))

array([[24, 30, 26, 25, 14],
       [12, 19, 19, 14, 22],
       [20, 22, 28, 23, 24]])