In [2]:
import numpy as np

Os arrays podem ter mais que duas dimensões, sendo também de 3 e 4 dimensões, onde estas últimas são bem difíceis de visualizar mentalmente e são bastante usadas em redes neurais.

Abaixo, temos 3 arrays 2d = 2 arrays de 2 linhas e 2 colunas, que geram um array 3d = 3 arrays de 2 linhas e 2 colunas. Um array 3d é composto de altura, largura e comprimento/profundidade.
Os arrays abaixo estão em formato de lista.

In [3]:
arr1_2d = np.array([[1,2],[3,4]])
arr2_2d = np.array([[5,6],[7,8]])
arr3_2d = np.array([[9,2],[3,4]])

arr_3d = np.array([arr1_2d, arr2_2d, arr3_2d])
arr_3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]],

       [[9, 2],
        [3, 4]]])

Arrays de 4 dimensões não são visíveis. Temos o código abaixo, mas sua visualização gráfica não é possível.

In [ ]:
arr1 = np.array([arr_3d, arr_3d])
arr1

array([[[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]],

        [[9, 2],
         [3, 4]]],


       [[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]],

        [[9, 2],
         [3, 4]]]])

Vetores - Array 3D
Programadores e a documentação do numpy se referem ao array como vetores, tensores ou matrizes. Termos matemáticos.
Os vetores, dentro do numpy, se referem ao array como de uma dimensão só ex: shape(4,) que pode ser uma linha e 4 colunas OU 1 coluna e 4 linhas.
Para criar um array que seja expecificamente vertical ou horizontal, precisamos colocar a ordem de como queremos, linhas e colunas.
Na matemática, podemos considerar coisas 2D como matrizes e 3D como tensores.



Atributos e métodos do array:

Atributos são propriedades qe geram valores e resultados, características do objeto. .shape = mostra quantas linhas e quantas colunas tem o array.

Os métodos geram ações, como achatar array, transformar dimensões etc. .flatten = achata a array, transformando em um array de uma dimensão (como uma lista). .reshape = muda as dimensões do array, uma que teria 2 linhas e 3 colunas, será remodelada para 3 linhas e 2 colunas. Nesse caso, não pode haver mudança no número de elementos, se eu tenho um array de 4 linhas e 3 colunas, isso terá 12 elementos, só posso remodelar para um array com 12 elementos, ex: 6 linhas e 2 colunas.


In [ ]:
arr1.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 2, 3, 4, 1, 2, 3, 4, 5, 6, 7, 8, 9, 2,
       3, 4])

In [ ]:
arr = np.zeros((3, 4, 2))
arr

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [ ]:
arr.shape

(3, 4, 2)

In [ ]:
arr.flatten()

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0.])

Array com 3 dimensões:


In [3]:
arr1_2d = np.array([[1,2],[3,4]])
arr2_2d = np.array([[5,6],[7,8]])
arr3_2d = np.array([[9,2],[3,4]])

arr_3d = np.array([arr1_2d, arr2_2d, arr3_2d])

In [4]:
arr_3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]],

       [[9, 2],
        [3, 4]]])

Array com 4 dimensões:

In [5]:
np.array([arr_3d, arr_3d])

array([[[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]],

        [[9, 2],
         [3, 4]]],


       [[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]],

        [[9, 2],
         [3, 4]]]])

Array de zeros com 3 dimensões:

Quantidade de dimensões (profundidade/comprimento), linhas(altura) e colunas(largura)


In [12]:
arr = np.zeros((3, 4, 2))
arr

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [10]:
arr.shape

(3, 4, 2)

In [13]:
arr.flatten()

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0.])

1 - Reduza uma array (5, 7) para apenas uma dimensão.

In [22]:
a57 = np.random.randint(1,25, size=(5, 7))
a57

array([[21, 14, 21, 12,  3,  2, 13],
       [24,  9, 12, 14,  4, 22,  2],
       [ 9,  3,  1, 22, 14,  9, 10],
       [ 1, 21, 23, 20, 20,  5, 15],
       [12, 18, 16,  1,  7, 15, 20]])

In [25]:
a57 = a57.flatten()
a57

array([21, 14, 21, 12,  3,  2, 13, 24,  9, 12, 14,  4, 22,  2,  9,  3,  1,
       22, 14,  9, 10,  1, 21, 23, 20, 20,  5, 15, 12, 18, 16,  1,  7, 15,
       20])

2 - Considerando que você é uma organizadora de um jogo de bingo. Crie um array que irá representar a cartilha desses jogos de bingo. Os números das suas cartelas variam entre 1 a 30, e você terá 10 participantes. Cada cartela terá 12 números (4,3).
Crie um array que represente esse jogo.

In [27]:
abingo = np.random.randint(1,31, size=(10, 4, 3))
abingo

array([[[ 9, 24,  1],
        [13, 10, 20],
        [27, 10,  7],
        [24,  2, 15]],

       [[ 4, 26,  6],
        [ 5, 10, 22],
        [17, 25,  5],
        [17, 27, 21]],

       [[28, 27, 12],
        [ 3, 30,  9],
        [19,  9,  3],
        [12,  2, 19]],

       [[24, 24,  9],
        [11,  8, 14],
        [ 2, 20,  2],
        [15, 29, 14]],

       [[ 7, 20, 18],
        [ 8, 18, 11],
        [23, 17,  3],
        [ 7,  4, 26]],

       [[28,  5, 23],
        [20,  7, 25],
        [23,  2, 28],
        [17, 29, 16]],

       [[25, 13, 27],
        [ 5,  2,  3],
        [18, 29,  6],
        [ 2, 13, 21]],

       [[21, 28,  3],
        [ 1, 27, 11],
        [ 2, 11, 21],
        [18,  3,  1]],

       [[20, 25, 26],
        [25, 28,  7],
        [15, 30, 20],
        [ 5, 21, 10]],

       [[26, 10, 25],
        [24, 16,  4],
        [24,  6,  3],
        [18, 10, 11]]])

3 - Faça o reshape das suas cartelas para que haja 5 cartelas de 4 linhas e 6 colunas.

In [30]:
abingo = abingo.reshape((5, 4, 6))
abingo

array([[[ 9, 24,  1, 13, 10, 20],
        [27, 10,  7, 24,  2, 15],
        [ 4, 26,  6,  5, 10, 22],
        [17, 25,  5, 17, 27, 21]],

       [[28, 27, 12,  3, 30,  9],
        [19,  9,  3, 12,  2, 19],
        [24, 24,  9, 11,  8, 14],
        [ 2, 20,  2, 15, 29, 14]],

       [[ 7, 20, 18,  8, 18, 11],
        [23, 17,  3,  7,  4, 26],
        [28,  5, 23, 20,  7, 25],
        [23,  2, 28, 17, 29, 16]],

       [[25, 13, 27,  5,  2,  3],
        [18, 29,  6,  2, 13, 21],
        [21, 28,  3,  1, 27, 11],
        [ 2, 11, 21, 18,  3,  1]],

       [[20, 25, 26, 25, 28,  7],
        [15, 30, 20,  5, 21, 10],
        [26, 10, 25, 24, 16,  4],
        [24,  6,  3, 18, 10, 11]]])