In [2]:
import numpy as np

Manipulando Array

Index em um array de 1 dimensão

In [3]:
arr = np.array([2, 4, 6, 8])
arr[2]

6

Index em um array de 2 dimensões

selecionar número específico em uma linha e coluna

In [12]:
arr = np.array([[ 9, 24,  1],
                [13, 10, 20],
                [27, 10,  7],
                [24,  2, 15]])
arr[1, 2]

20

selecionar uma linha inteira

In [13]:
arr[0]

array([ 9, 24,  1])

selecionar coluna inteira

In [15]:
arr[:, 1]

array([24, 10, 10,  2])

Fatiar (slicing) um array de 2 dimensões

COm o exemplo a baixo, as localizações ficam = linha 1 e coluna 0 + linha 2 (3-1) e coluna 1 (2-1). Essas localizações dariam os números 13 e 10, contando os que fazem margem com ambos.

In [17]:
arr[1:3, 0:2]

array([[13, 10],
       [27, 10]])

Ordenar (sorting) um array

ordena linha por linha

In [18]:
np.sort(arr)

array([[ 1,  9, 24],
       [10, 13, 20],
       [ 7, 10, 27],
       [ 2, 15, 24]])

Quais são os eixos (axis)

axis 0 - eixo vertical

axis 1 - eixo horizontal

Agora podemos usar o sort para ordenar de acordo com o eixo desejado


Vertical

In [19]:
np.sort(arr, axis=0)

array([[ 9,  2,  1],
       [13, 10,  7],
       [24, 10, 15],
       [27, 24, 20]])

Horizontal

In [20]:
np.sort(arr, axis=1)

array([[ 1,  9, 24],
       [10, 13, 20],
       [ 7, 10, 27],
       [ 2, 15, 24]])

Atividade - Explorando Exossistemas:
Como bióloga marinha, me encontrei em uma expedição nas profundezas do Oceano Pacífico, onde estávamos estudando a biodiversidade e a saúde dos recifes de coral. O catálogo abaixo demonstra dados das espécies encontradas, considere a seguinte ordem de colunas:

ID da espécie, quantidade de representantes encontrados, profundeza, tamanho médio da espécie

Selecione a segunda coluna com a quantidade de espécies encontradas e adicione em um arrey como 'qtd_especies'

De qtd_especies selecione apenas as primeiras 3 quantidades e print

Print as 5 últimas quantidades de espécies

Crie um array que contenha paenas os tamanhos das espécies e ordene por ordem crescente

In [25]:
especies = np.array([[747, 89, 33, 5],
                    [623, 123, 32, 13],
                    [501, 22, 49, 2],
                    [116, 101, 42, 10],
                    [297, 56, 69, 22],
                    [613, 64, 27, 7],
                    [295, 84, 29, 14],
                    [692, 105, 72, 16],
                    [229, 103, 35, 5],
                    [374, 124, 70, 1]])
especies

array([[747,  89,  33,   5],
       [623, 123,  32,  13],
       [501,  22,  49,   2],
       [116, 101,  42,  10],
       [297,  56,  69,  22],
       [613,  64,  27,   7],
       [295,  84,  29,  14],
       [692, 105,  72,  16],
       [229, 103,  35,   5],
       [374, 124,  70,   1]])

Selecione a segunda coluna com a quantidade de espécies encontradas e adicione em um arrey como 'qtd_especies'

In [26]:
qtd_especies = especies[:, 1]
qtd_especies

array([ 89, 123,  22, 101,  56,  64,  84, 105, 103, 124])

De qtd_especies selecione apenas as primeiras 3 quantidades e print

In [31]:
print(qtd_especies[0:3])

[ 89 123  22]


Print as 5 últimas quantidades de espécies

In [36]:
print(qtd_especies[5:10])

[ 64  84 105 103 124]


  Também pode ser feito da seguinte forma, gerando um array:

  Essa técnica ajuda muito quando temos uma quantidade imensa de dados, pois vai direto para os últimos dados, sem qeu você precise ficar contabilizando linhas e quantidade de elementos.


In [37]:
qtd_especies[-5:]

array([ 64,  84, 105, 103, 124])

Crie um array que contenha apenas os tamanhos das espécies e ordene por ordem crescente

O tamanho das espécies é a coluna 4, sendo reconhecida como 3.

In [39]:
np.sort(especies[:, 3])

array([ 1,  2,  5,  5,  7, 10, 13, 14, 16, 22])

Crie um array que contenha apenas os tamanhos das espécies e ordene, agora, por ordem decrescente

O tamanho das espécies é a coluna 4, sendo reconhecida como 3.

[::-1] - Array em ordem decrescente no range de python

In [ ]:
np.sort(especies[:, 3])[::-1]