In [2]:
import numpy as np

Concatenação = União de coisas, pode ser listas, arrays, strings etc

Concatenando linhas - adicionar uma linha logo abaixo de outra na array

O Array indicado no inicio fica por cima e logo após os subsequentes.

np.concatenate((arrv1, arrv2))





In [3]:
arrv1 = np.random.randint(10, size=(3,2))
arrv1

array([[8, 6],
       [5, 9],
       [7, 1]])

In [4]:
arrv2 = np.array([["Peras", "Morangos"]])
arrv2

array([['Peras', 'Morangos']], dtype='<U8')

In [5]:
np.concatenate((arrv1, arrv2))

array([['8', '6'],
       ['5', '9'],
       ['7', '1'],
       ['Peras', 'Morangos']], dtype='<U21')

Concatenação de colunas - usamos o axis=1

In [6]:
arrv1

array([[8, 6],
       [5, 9],
       [7, 1]])

In [7]:
arro1 = np.array(["Uva", "Abacaxi", "Laranja"]).reshape((3, 1))
arro1

array([['Uva'],
       ['Abacaxi'],
       ['Laranja']], dtype='<U7')

In [8]:
np.concatenate((arrv1, arro1), axis=1)

array([['8', '6', 'Uva'],
       ['5', '9', 'Abacaxi'],
       ['7', '1', 'Laranja']], dtype='<U21')

SE TENTARMOS CONCATENAR LINHAS E COLUNAS EM QUANTIDADES QUE NÃO SÃO EQUIVALENTES AO OUTRO ARRAY, DARÁ ERRO

exemplo, se um array com 3 linhas e 4 colunas eu queira adicionar um array com 2 linhas e 3 colunas. Isso também nos diz que precisamos informar todos os matches, como se tenho um array com 3 linhas e 4 colunas eu queira adicionar um array com 3 linhas e 1 coluna, preciso informar o shape como (4, 1) e não somente (4,)

É possível adicionar arrays para criar novas dimensões, mas o método np.concatenate não permite. Além disso, só é compatível para as mesmas dimensões já existentes no array.

Deletando com axis=0 e com axis=1

In [14]:
sala_de_espera = np.array([['5', '30', '1', 'Alice'],
                       ['6', '29', '1', 'Bob'],
                       ['7', '35', '3', 'Cristina'],
                       ['8', '34', '3', 'Luiz']])
sala_de_espera

array([['5', '30', '1', 'Alice'],
       ['6', '29', '1', 'Bob'],
       ['7', '35', '3', 'Cristina'],
       ['8', '34', '3', 'Luiz']], dtype='<U8')

In [15]:
np.delete(sala_de_espera, 2, axis=0)

array([['5', '30', '1', 'Alice'],
       ['6', '29', '1', 'Bob'],
       ['8', '34', '3', 'Luiz']], dtype='<U8')

In [16]:
np.delete(sala_de_espera, 1, axis=1)

array([['5', '1', 'Alice'],
       ['6', '1', 'Bob'],
       ['7', '3', 'Cristina'],
       ['8', '3', 'Luiz']], dtype='<U8')

Cálculos com Arrays

Métodos de agregação de dados

Python - .sum()  |  .min()  |  .max()  |  .mean()  |  .cumsum()

Temos dados de acidentes, onde cada coluna é um cliente e cada linha é um ano.



In [34]:
acidentes = np.array(([1, 3, 2],
                     [0, 1, 0],
                     [2, 1, 4],
                     [0, 0, 0],
                     [1, 1, 0]))
acidentes

array([[1, 3, 2],
       [0, 1, 0],
       [2, 1, 4],
       [0, 0, 0],
       [1, 1, 0]])

Se eu quiser somar tudo, uso .sum() que irá somar o array inteiro

In [35]:
acidentes.sum()

16

Se eu quiser somar colunas, uso .sum(axis=0) que irá somar as colunas separadamente

In [36]:
acidentes.sum(axis=0)

array([4, 6, 6])

Se eu quiser somar linhas, uso .sum(axis=1) que irá somar as linhas separadamente

In [37]:
acidentes.sum(axis=1)

array([6, 1, 7, 0, 2])

Mostrar os mínimos e máximos do array


In [38]:
acidentes.min()

0

In [39]:
acidentes.max()

4

Máximo de cada linha

In [40]:
acidentes.max(axis=0)

array([2, 3, 4])

Máximo de cada coluna

In [41]:
acidentes.max(axis=1)

array([3, 1, 4, 0, 1])

Média


In [42]:
acidentes.mean()

1.0666666666666667

In [43]:
acidentes.mean(axis=0)

array([0.8, 1.2, 1.2])

In [44]:
acidentes.mean(axis=1)

array([2.        , 0.33333333, 2.33333333, 0.        , 0.66666667])

Método keepsims - manter as mesmas dimensões da array

In [45]:
acidentes.mean(axis=0)

array([0.8, 1.2, 1.2])

In [46]:
acidentes.mean(axis=0, keepdims=True)

array([[0.8, 1.2, 1.2]])

In [47]:
acidentes.mean(axis=1)

array([2.        , 0.33333333, 2.33333333, 0.        , 0.66666667])

In [48]:
acidentes.mean(axis=1, keepdims=True)

array([[2.        ],
       [0.33333333],
       [2.33333333],
       [0.        ],
       [0.66666667]])

Soma cumulativa - cumcum()

É interessante para fazer plotagem de histórico

In [49]:
acidentes.cumsum(axis=0)

array([[1, 3, 2],
       [1, 4, 2],
       [3, 5, 6],
       [3, 5, 6],
       [4, 6, 6]])

In [50]:
acidentes.cumsum(axis=1)

array([[1, 4, 6],
       [0, 1, 1],
       [2, 3, 7],
       [0, 0, 0],
       [1, 2, 2]])

Atividade - Ainda no conjunto 'especies'

Adicione mais 2 espécies ao array:[[204,10,40,12],[392,11,81,11]

Adicione mais uma coluna ao array original, agora com o número de espécies encontradas, que indica se o animal enxerga ou não: [0,1,0,0,0,0,1,0,1,1,0]




Adicione mais 2 espécies ao array:[[204,10,40,12],[392,11,81,11]

In [53]:
especies = np.array([[747, 89, 33, 5],
                    [623, 123, 32, 13],
                    [501, 22, 49, 2],
                    [116, 101, 42, 10],
                    [297, 56, 69, 22],
                    [613, 64, 27, 7],
                    [295, 84, 29, 14],
                    [692, 105, 72, 16],
                    [229, 103, 35, 5],
                    [374, 124, 70, 1]])
especies

array([[747,  89,  33,   5],
       [623, 123,  32,  13],
       [501,  22,  49,   2],
       [116, 101,  42,  10],
       [297,  56,  69,  22],
       [613,  64,  27,   7],
       [295,  84,  29,  14],
       [692, 105,  72,  16],
       [229, 103,  35,   5],
       [374, 124,  70,   1]])

In [55]:
novas_especies = np.array([[204, 10, 40, 12], [392, 11, 81, 11]])

In [57]:
np.concatenate((especies, novas_especies))

array([[747,  89,  33,   5],
       [623, 123,  32,  13],
       [501,  22,  49,   2],
       [116, 101,  42,  10],
       [297,  56,  69,  22],
       [613,  64,  27,   7],
       [295,  84,  29,  14],
       [692, 105,  72,  16],
       [229, 103,  35,   5],
       [374, 124,  70,   1],
       [204,  10,  40,  12],
       [392,  11,  81,  11]])

Adicione mais uma coluna ao array original, agora com o número de espécies encontradas, que indica se o animal enxerga ou não: [0,1,0,0,0,0,1,0,1,1,0]

In [61]:
ver = np.array([0,1,0,0,0,0,1,0,1,1]).reshape((10,1))
ver

array([[0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1]])

In [63]:
np.concatenate((especies, ver), axis=1)

array([[747,  89,  33,   5,   0],
       [623, 123,  32,  13,   1],
       [501,  22,  49,   2,   0],
       [116, 101,  42,  10,   0],
       [297,  56,  69,  22,   0],
       [613,  64,  27,   7,   0],
       [295,  84,  29,  14,   1],
       [692, 105,  72,  16,   0],
       [229, 103,  35,   5,   1],
       [374, 124,  70,   1,   1]])