In [2]:
import numpy as np

Tipos em Python

Int e Float

Tipos em NumPy

np.int64
np.int32
np.float64
np.float32

O 64 bits será usado para 64 bits e o 32 para 32. Isso é feito para economizar memória. Se tenho uma array quen não necessita 64 bits não pe necessário alocar em 64 bits.

Bits unidade binária, menor unidade de dados de um computador, 0 ou 1.

Bytes é uma sequência de 8 Bits.

2024 em binário = 0000011111101000 = 2bytes

Fica armazenado na np.int32 que armazena 4.294.967.296 bits em valor inteiro = 2³²

Dividio metade para mais e metade para menos.

Quando é 64, fica 2 elevado a 64, gerando um número MUITO maior.



Atributo .dtype e tipo default

Esse atributo indica qual é o tipo dos elementos que estão sendo guardados.

In [3]:
np.array([2.14, 6.25, 160.87, 8.4]).dtype

dtype('float64')

In [4]:
np.array([2, 6, 160 , 8]).dtype

dtype('int64')

Dados tipo String são expressados de forma um pouco diferente:

In [7]:
np.array(["Hello", "Coder", "Girls"]).dtype

dtype('<U5')

O valor gerado foi o <U5, pois as palavras contém 5 letras.

Se no meio das palavras de 5 letras, tivesse alguma com mais letras, seria considerado esse valor como U

In [8]:
np.array(["Hello", "Coders", "Girls"]).dtype

dtype('<U6')

Conversão e coerção

dtype como argumento:

In [13]:
arr_float32 = np.array([2.14, 6.25, 160.87, 8.4], dtype=np.float32)
arr_float32

array([  2.14,   6.25, 160.87,   8.4 ], dtype=float32)

Conversão - Tudo que é false é 0 e tudo que é true é 1, ver tabela verdade.

In [14]:
arr_vf = np.array ([[True, False], [True, True]], dtype=np.bool8)
arr_vf.astype(np.int32)

array([[1, 0],
       [1, 1]], dtype=int32)

Coerção

In [15]:
np.array(["pedra", False, 42, 42.42])

array(['pedra', 'False', '42', '42.42'], dtype='<U32')

Hierarquia de coerção

Adicionar um float a um array de int mudará todos os valores para float.

In [16]:
np.array([0, 10]).dtype

dtype('int64')

In [17]:
np.array([0, 10, 1.]).dtype

dtype('float64')

Adicionar um inteiro em um array de booleanos transformará todo o array em itneiros

In [18]:
np.array([True, False]).dtype

dtype('bool')

In [19]:
np.array([True, False, 12]).dtype

dtype('int64')

Tipos de dados em um NumPy Array

In [20]:
np.array([5.4, 6.7, 2.1]).dtype

dtype('float64')

In [21]:
np.array([5, 6, 2]).dtype

dtype('int64')

In [22]:
np.array(["Hello", "Oi", "WoMakersCode"]).dtype

dtype('<U12')

In [23]:
np.array([3, 4, 2.1]).dtype

dtype('float64')

In [24]:
np.array([True, 3, False]).dtype

dtype('int64')

In [27]:
vf = np.array([True, 3, False])
vf

array([1, 3, 0])

In [28]:
vf.astype(np.float32)

array([1., 3., 0.], dtype=float32)

In [30]:
vf.astype(np.bool8)

array([ True,  True, False])